# Site settings
title: Roger Stringer
email: roger.stringer@me.com
description: > # this means to ignore newlines until "baseurl:"
  I’m Roger Stringer, and I’m a DevOps Engineer, full-stack software developer, writer, and speaker in Penticton, British Columbia, Canada.
  This blog is where I write and share. You will see everything from reviews, posts about tech and design, to food.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://archived.rogerstringer.com" # the base hostname & protocol for your site
twitter_username: freekrai
github_username:  freekrai

# Build settings
#markdown: kramdown
encoding: utf-8
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
paginate: 20
permalink: pretty

gems:
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
